version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: qaapp-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-qa_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qa_password}
      POSTGRES_DB: ${POSTGRES_DB:-qa_database}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 20

  # Optional Redis cache (disabled by default in .env)
  redis:
    image: redis:7-alpine
    container_name: qaapp-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  redisdata:
