# Istio 安装配置
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: qa-app-istio
  namespace: istio-system
spec:
  # 全局配置
  values:
    global:
      meshID: qa-app-mesh
      multiCluster:
        clusterName: qa-app-cluster
      network: qa-app-network
    pilot:
      traceSampling: 1.0 # 开发环境100%采样，生产环境建议1-5%
    
  # 组件配置
  components:
    # 控制平面
    pilot:
      k8s:
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        hpaSpec:
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 80
    
    # 入口网关
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
                protocol: TCP
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
              - port: 15443
                targetPort: 15443
                name: tls
                protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
    
    # 出口网关 (可选)
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
# 启用自动sidecar注入
apiVersion: v1
kind: Namespace
metadata:
  name: qa-app
  labels:
    istio-injection: enabled
---
# Istio配置 - 全局网格策略
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: qa-app
spec:
  mtls:
    mode: STRICT # 强制mTLS
---
# 网格配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |
    # 全局配置
    defaultConfig:
      # 代理配置
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*circuit_breakers.*"
          - ".*upstream_rq_retry.*"
          - ".*_cx_.*"
        exclusionRegexps:
          - ".*osconfig.*"
      # 链路追踪
      tracing:
        zipkin:
          address: "jaeger-collector.istio-system.svc.cluster.local:9411"
      # 访问日志
      accessLogFile: "/dev/stdout"
      accessLogEncoding: JSON
      accessLogFormat: |
        {
          "timestamp": "%START_TIME%",
          "method": "%REQ(:METHOD)%",
          "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "protocol": "%PROTOCOL%",
          "response_code": "%RESPONSE_CODE%",
          "response_flags": "%RESPONSE_FLAGS%",
          "bytes_received": "%BYTES_RECEIVED%",
          "bytes_sent": "%BYTES_SENT%",
          "duration": "%DURATION%",
          "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
          "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
          "user_agent": "%REQ(USER-AGENT)%",
          "request_id": "%REQ(X-REQUEST-ID)%",
          "authority": "%REQ(:AUTHORITY)%",
          "upstream_host": "%UPSTREAM_HOST%",
          "upstream_cluster": "%UPSTREAM_CLUSTER%",
          "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
          "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
          "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
          "requested_server_name": "%REQUESTED_SERVER_NAME%",
          "route_name": "%ROUTE_NAME%"
        }
    # 扩展提供者
    extensionProviders:
      - name: jaeger
        envoyOtelAls:
          service: jaeger-collector.istio-system.svc.cluster.local
          port: 14250
      - name: prometheus
        prometheus: {}
---
# Telemetry v2 配置
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
  namespace: qa-app
spec:
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100.0
  accessLogging:
    - providers:
        - name: envoy